# 项目信息
site_name: FlitSoft Doc Hub
site_url: https://flitsoftdoc.github.io/
site_author: flitsoftdoc
site_description: >-
 FlitSoft Documents

# 仓库信息
repo_url: https://github.com/flitsoftdoc/flitsoftdoc.github.io
repo_name: flitsoftdoc/flitsoftdoc.github.io

# 编辑链接配置
edit_uri: edit/main/docs/

# 主题配置
theme:
  name: material
  logo: /assets/logo/logo.png
  favicon: /assets/logo/HB logo.png
  font: false            # 禁用从 Google 自动加载

extra_css:
  - stylesheets/extra.css

  # 自定义配色和功能 (可选)
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    # - content.action.edit    # 显示“编辑此页”
    - content.action.view    # 显示“查看源码”（仅 GitHub 支持）

# 插件
plugins:
  - search


# 新增部分：加载 MathJax 的 JavaScript 库
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Markdown 扩展
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
