# 项目信息
site_name: 我的文档网站
site_url: https://flitsoftdoc.github.io/
site_author: flitsoftdoc
site_description: >-
  一个用 MkDocs Material 搭建的文档网站

# 仓库信息
repo_url: https://github.com/flitsoftdoc/flitsoftdoc.github.io
repo_name: flitsoftdoc/flitsoftdoc.github.io

# 主题配置
theme:
  name: material
  # 自定义配色和功能 (可选)
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy

# 插件
plugins:
  - search

# Markdown 扩展
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true