# 项目信息
site_name: FlitSoft Doc Hub
site_url: https://flitsoftdoc.github.io/
site_author: flitsoftdoc
site_description: >-
  FlitSoft Documents

# 仓库信息
repo_url: https://github.com/flitsoftdoc/flitsoftdoc.github.io
repo_name: flitsoftdoc/flitsoftdoc.github.io

# 编辑链接配置
edit_uri: edit/main/docs/

# 插件
plugins:
  - search
  - awesome-nav
  - pseudocode   

# 主题配置
theme:
  name: material
  logo: /assets/logo/grid.png
  favicon: /assets/logo/grid.png    # 含空格，建议加引号（或把文件重命名去掉空格）
  font: false
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.path
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - content.tabs.link
    - content.code.annotate
    - content.code.copy
    # - content.action.edit
    - content.action.view
    - navigation.indexes   # 目录点击进入 index.md

# 额外样式
extra_css:
  - stylesheets/extra.css
  - stylesheets/pseudo-code.css


# 额外脚本（MathJax）
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Markdown 扩展
markdown_extensions:
  - pymdownx.blocks.admonition      # 支持 /// admonition | Title
  - pymdownx.blocks.details       # 可选：支持 /// details | Title 折叠块
  - pymdownx.blocks.tab
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: false                   # 可选：显示行号
      # 其他可选项（按需启用）：
      # line_spans: __span
      # pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list # 支持属性列表（如：`{.class #id}`）让链接新窗口打开（需要启用 attr_list 扩展）
  - pymdownx.magiclink # 支持自动链接（如：`https://example.com`）
  - md_in_html

extra:
  generator: false