# docs/.nav.yml
append_unmatched: false   # 想让未列出的目录自动追加就改为 true
nav:
  # - Home: index.md       # ← 把首页显式加入导航
  - UAS
  - EM
  - AI
  - Decision: Gaming
  - NGC3: C2
  - Simulation: Simu
  - Visualization: Visual   # 左边是显示名，右边是实际目录
  - Blog:
    - Blog/index.md
  

