# docs/.nav.yml
append_unmatched: false   # 想让未列出的目录自动追加就改为 true
nav:
  - UAS
  - EM
  - AI
  - Decision Making: Gaming
  - NGC2: C2
  - Simulation: Simu
  - Visualization: Visual   # 左边是显示名，右边是实际目录
  

